name: www.michelkammoun.com
favicon: null
layout_spectrum: 0.827440673019737
typography_spectrum: 0.51156
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: michel kammoun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3730'
    - '#d6d7d2'
    - '#a4a5a0'
    - '#5c5952'
    - '#7e7f7a'
  brandStrength: 0.2169892191886902
  lightness: 0.1437986090313643
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
